### ISSUE TITLE
ofi_monitor_cleanup: Assertion error

### ISSUE THREAD

**Issue by kwaters4** [pnnl/rofi#1]
When running a lamellar program in parallel there is an error when the program attempts to finish.
I believe it is somewhere between ROFI and libfabric.

The example rust program is running to completion and then the following error occurs:

test_app: prov/util/src/util_mem_monitor.c:84: ofi_monitor_cleanup: Assertion `dlist_empty(&monitor->list)' failed.

libfabric version : 1.15.0

I can provide more details, just let me know.

**Comment by rdfriese** [comment]
I committed a fix to Rofi (on master) and to Lamellar (on dev) as there were some issues in both, hopefully the should cleanup properly now!

**Comment by kwaters4** [comment]
Thanks, I will try to rebuild and test the fixes the week.

**Comment by kwaters4** [comment]
Thanks, I will rebuild and test it this week.

**Comment by kwaters4** [comment]
Rebuilt ROFI from master and used the old version as well. 

Had some issue running make test this time around, still trying to identify what is the cause of this. Looks like it may be my end.

However, using the following line in my Cargo.toml
`lamellar = { git = "https://github.com/pnnl/lamellar-runtime", branch = "dev", features = ["enable-rofi"]}`
the error went away for both versions of ROFI.

Thanks!
